name: Betting Checker

on:
  schedule:
   - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch: # Allows manual execution

jobs:
  run-betting-script:
    runs-on: ubuntu-latest
    timeout-minutes: 60  # Ensures it doesn't exceed 1 hour

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'


      - name: Set up Maven
        run: mvn -v  # Check Maven installation

      - name: Build and Compile Project
        run: mvn clean package

      - name: Run Java application
        run: java -cp target/Bettings-1.0-SNAPSHOT.jar org.example.Main
